name:          Digital Additive Code Guide
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://digital-additive.github.io

markdown:      rdiscount
permalink:     pretty
pygments:      true
